version: '3.7'
services:
  app:
    image: vue-ts-app
    build:
      context: .
    container_name: vue-ts-app
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
      - ./docs:/docs
    working_dir: /app
    #command: npm run serve
